workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up debug keychain
        script: keychain initialize
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: flutter analyze

      - name: Build ipa for distribution
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload
          zip -r app.ipa Payload
    artifacts:
      - build/ios/iphoneos/app.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
