name: attendance_tracker
description: A simple attendance debt tracking app

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  get: ^4.6.5
  provider: ^6.0.6

  # Additional template dependencies
  cached_network_image: ^3.2.3
  cookie_jar: ^3.0.1
  date_format: ^2.0.2
  devicelocale: ^0.4.2
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  extended_image: ^4.0.1
  event_bus: ^2.0.0
  flutter_easyrefresh: ^2.1.6
  flutter_spinkit: ^5.1.0
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.4.0
  flutter_xupdate: ^2.0.2
  image_picker_saver: ^0.3.0
  oktoast: ^3.0.0
  path_provider: ^2.0.11
  package_info: ^2.0.2
  permission_handler: ^10.2.0
  share: ^2.0.4
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: xuifont
      fonts:
        - asset: assets/fonts/iconfont.ttf
